Add scripts listing

diff --git a/rootfs/opt/qserv/bin/qserv-kubectl b/rootfs/opt/qserv/bin/qserv-kubectl
--- a/rootfs/opt/qserv/bin/qserv-kubectl
+++ b/rootfs/opt/qserv/bin/qserv-kubectl
@@ -5,7 +5,6 @@
 # @author  Fabrice Jammes
 
 set -e
-set -x
 
 DIR=$(cd "$(dirname "$0")"; pwd -P)
 
@@ -13,7 +12,7 @@ usage() {
     cat << EOD
 Usage: $(basename "$0") [options]
 Available options:
-  -C            Command to launch inside container
+  -C            Kubectl command to launch
   -K            Path to configuration directory, default to
                 \$CLUSTER_CONFIG_DIR env variable value
   -h            This message
@@ -23,7 +22,6 @@ kubectl, ...) and scripts.
 
 EOD
 }
-set -x
 
 # Get the options
 while getopts hC:K: c ; do
@@ -59,5 +57,12 @@ K8S_SCRIPTS_DIR=$QSERV_INSTALL_DIR/k8s/kubectl/admin
 
 # Load VERSION variable (i.e. version of qserv/qserv to use)
 . "$CLUSTER_CONFIG_DIR"/env.sh
+
+if [ -z "${CMD}" ] || [ ! -x "$K8S_SCRIPTS_DIR/${CMD}" ]; then
+    echo "ERROR: Invalid command: ${CMD}"
+    echo "Available commands:"
+    find $K8S_SCRIPTS_DIR -type f -perm -111 -printf "%f\n"
+    exit 2
+fi
 
 $K8S_SCRIPTS_DIR/${CMD}
diff --git a/rootfs/opt/qserv/bin/qserv-sysadmin b/rootfs/opt/qserv/bin/qserv-sysadmin
--- a/rootfs/opt/qserv/bin/qserv-sysadmin
+++ b/rootfs/opt/qserv/bin/qserv-sysadmin
@@ -6,7 +6,6 @@
 # @author  Benjamin Roziere <benjamin.roziere@clermont.in2p3.fr>
 
 set -e
-set -x
 
 DIR=$(cd "$(dirname "$0")"; pwd -P)
 
@@ -44,5 +43,12 @@ if [ ! -d "$CLUSTER_CONFIG_DIR" ]; then
 fi
 
 SYSADMIN_SCRIPTS_DIR=$QSERV_INSTALL_DIR/k8s/sysadmin
+
+if [ -z "${CMD}" ] || [ ! -x "$SYSADMIN_SCRIPTS_DIR/${CMD}" ]; then
+    echo "ERROR: Invalid command: ${CMD}"
+    echo "Available commands:"
+    find $SYSADMIN_SCRIPTS_DIR -type f -perm -111 -printf "%f\n"
+    exit 2
+fi
 
 $SYSADMIN_SCRIPTS_DIR/${CMD}
